DROP DATABASE IF EXISTS BAMAZON_DB;

CREATE DATABASE BAMAZON_DB;

USE BAMAZON_DB;

CREATE TABLE DEPARTMENT(
	DEPT_ID INT NOT NULL AUTO_INCREMENT,
    DEPT_NAME VARCHAR(25) NOT NULL, 
    PRIMARY KEY(DEPT_ID)
    );

CREATE TABLE PRODUCTS(
    ITEM_ID INT NOT NULL AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    DEPT_ID INT NOT NULL,
    PRICE DECIMAL(6, 2),
    STOCK_QUANTITY INTEGER,
    PRIMARY KEY(ITEM_ID)
);


    ALTER TABLE PRODUCTS
	ADD FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID); 

    INSERT INTO DEPARTMENT (DEPT_NAME)
    VALUES ('PETS');
    
    INSERT INTO DEPARTMENT (DEPT_NAME)
    VALUES ('HARDWARE');
    
    INSERT INTO DEPARTMENT (DEPT_NAME)
    VALUES ('KITCHEN'), ('BATH'), ('ELECTRONICS'), ('OFFICE'), ('GARDEN');
    
    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPT_ID,PRICE,STOCK_QUANTITY)
    VALUES("DOG BED, LG", 1, 29.99, 1);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPT_ID,PRICE,STOCK_QUANTITY)
    VALUES("2IN. ANGLED PAINTBRUSH", 2, 8.99, 10);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPT_ID,PRICE,STOCK_QUANTITY)
    VALUES("14IN. SKILLET", 3, 29.99, 5);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPT_ID,PRICE,STOCK_QUANTITY)
    VALUES("PLUSH BATH TOWEL, LG", 4, 9.99, 25);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPT_ID,PRICE,STOCK_QUANTITY)
    VALUES("AMAZON ALEXA, 3IN. BT", 5, 49.99, 40);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPT_ID,PRICE,STOCK_QUANTITY)
    VALUES("70 PAGE SPIRAL/BOUND NOTEBOOK/COUNT 10", 6, 1.99, 50);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPT_ID,PRICE,STOCK_QUANTITY)
    VALUES("IPHONE LIGHTNING CHARGER", 5, 14.99, 12);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPT_ID,PRICE,STOCK_QUANTITY)
    VALUES("KEURIG COFFEE MAKER", 3, 89.99, 9);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPT_ID,PRICE,STOCK_QUANTITY)
    VALUES("10 PIECE SCREWDRIVER SET", 2, 19.99, 127);

    INSERT INTO PRODUCTS
        (PRODUCT_NAME, DEPT_ID,PRICE,STOCK_QUANTITY)
    VALUES("EXPANDABLE GARDEN HOSE, 50 FT", 7, 34.99, 77);